language: python
python:
  - "3.6"
before_install:
  - mv travis_secrets.yaml secrets.yaml
  - mv ssh-keys/travis_id_rsa ssh-keys/id_rsa
  - mv ssh-keys/travis_id_rsa.pub ssh-keys/id_rsa.pub
  - mkdir -p /ssl
  - touch /ssl/fullchain.pem
  - touch /ssl/privkey.pem
install:
  - pip3 install homeassistant
script:
  - hass -c . --script check_config
