###############################################################################
# PACKAGE:      Harmony
# Description:
###############################################################################
remote:
    platform: harmony
    name: Harmony Hub
    activity: 'Regarder Apple TV'

sensor:
    platform: template
    entity_id: remote.harmony_hub
    sensors:
        harmony_salon:
            value_template: '{{ states.remote.harmony_hub.attributes.current_activity }}'
            friendly_name: 'Harmony Salon'

#These inputs are mainly used as script flags
input_boolean:
    harmony_appletv:
        name: Regarder Apple TV
        icon: mdi:apple
    harmony_music:
        name: Écouter de la musique
        icon: mdi:music-circle
    harmony_ps4:
        name: Jouer à PS4
        icon: mdi:playstation
    harmony_switch:
        name: Jouer à la Switch
        icon: mdi:nintendo-switch
    harmony_chromecast:
        name: Regarder Chromecast
        icon: mdi:cast

input_select:
    harmony:
        name: Harmony Activities
        initial: PowerOff
        options:
          - Regarder Apple TV
          - Jouer à PS4
          - Jouer a la Switch
          - Écouter de la musique
          - Regarder Chromecast
          - PowerOff
