sensor:
  - platform: hue
  - platform: template
    sensors:
        lux_hue_cuisine:
            entity_id: binary_sensor.capteur_motion_cuisine
            friendly_name: Luminosité Cuisine (Hue Motion)
            unit_of_measurement: 'lux'
            value_template: '{{ float(10**((states.binary_sensor.capteur_motion_cuisine.attributes.light_level-1)/10000)) | round(0) }}'
        temp_hue_cuisine:
            entity_id: binary_sensor.capteur_motion_cuisine
            friendly_name: Température Cuisine (Hue Motion)
            unit_of_measurement: '°C'
            value_template: '{{ states.binary_sensor.capteur_motion_cuisine.attributes.temperature| round(1) }}'
        lux_hue_chambre:
            entity_id: binary_sensor.capteur_chambre_motion_ianto
            friendly_name: Luminosité Chambre Ianto (Hue Motion)
            unit_of_measurement: 'lux'
            value_template: '{{ float(10**((states.binary_sensor.capteur_chambre_motion_ianto.attributes.light_level-1)/10000)) | round(0) }}'
        temp_hue_chambre:
            entity_id: binary_sensor.capteur_chambre_motion_ianto
            friendly_name: Température Chambre Ianto (Hue Motion)
            unit_of_measurement: '°C'
            value_template: '{{ states.binary_sensor.capteur_chambre_motion_ianto.attributes.temperature| round(1) }}'
        battery_hue_switch_chambre_parents:
            entity_id: sensor.parents_chambre_interrupteur
            friendly_name: Batterie Hue Switch chambre parents
            unit_of_measurement: '%'
            value_template: '{{ states.sensor.parents_chambre_interrupteur.attributes.battery }}'
            icon_template: >-
                {% set battery_level = states('sensor.battery_hue_switch_chambre_parents')|int('unknown') %}
                {% set battery_round = (battery_level|int / 10)|int * 10 %}
                {% if battery_level == 'unknown' %}
                  mdi:battery-unknown
                {% else %}
                  {% if battery_round >= 100 %}
                    mdi:battery
                  {% elif battery_round > 0 %}
                    mdi:battery-{{ battery_round }}
                  {% else %}
                    mdi:battery-alert
                  {% endif %}
                {% endif %}
        battery_hue_switch_salon:
            entity_id: sensor.dimmer_switch_salon
            friendly_name: Batterie Hue Switch Salon
            unit_of_measurement: '%'
            value_template: '{{ states.sensor.dimmer_switch_salon.attributes.battery }}'
            icon_template: >-
                {% set battery_level = states('sensor.battery_hue_switch_salon')|int('unknown') %}
                {% set battery_round = (battery_level|int / 10)|int * 10 %}
                {% if battery_level == 'unknown' %}
                  mdi:battery-unknown
                {% else %}
                  {% if battery_round >= 100 %}
                    mdi:battery
                  {% elif battery_round > 0 %}
                    mdi:battery-{{ battery_round }}
                  {% else %}
                    mdi:battery-alert
                  {% endif %}
                {% endif %}
        battery_hue_switch_chambre_ianto:
            entity_id: sensor.interrupteur_chambre_de_ianto
            friendly_name: Batterie Hue Switch Chambre Ianto
            unit_of_measurement: '%'
            value_template: '{{ states.sensor.interrupteur_chambre_de_ianto.attributes.battery }}'
            icon_template: >-
                {% set battery_level = states('sensor.battery_hue_switch_chambre_ianto')|int('unknown') %}
                {% set battery_round = (battery_level|int / 10)|int * 10 %}
                {% if battery_level == 'unknown' %}
                  mdi:battery-unknown
                {% else %}
                  {% if battery_round >= 100 %}
                    mdi:battery
                  {% elif battery_round > 0 %}
                    mdi:battery-{{ battery_round }}
                  {% else %}
                    mdi:battery-alert
                  {% endif %}
                {% endif %}
        battery_hue_sensor_chambre_ianto:
            entity_id: binary_sensor.capteur_chambre_motion_ianto
            friendly_name: Batterie Hue sensor chambre Ianto
            unit_of_measurement: '%'
            value_template: '{{ states.binary_sensor.capteur_chambre_motion_ianto.attributes.battery }}'
            icon_template: >-
                {% set battery_level = states('sensor.battery_hue_sensor_chambre_ianto')|int('unknown') %}
                {% set battery_round = (battery_level|int / 10)|int * 10 %}
                {% if battery_level == 'unknown' %}
                  mdi:battery-unknown
                {% else %}
                  {% if battery_round >= 100 %}
                    mdi:battery
                  {% elif battery_round > 0 %}
                    mdi:battery-{{ battery_round }}
                  {% else %}
                    mdi:battery-alert
                  {% endif %}
                {% endif %}
        battery_hue_sensor_cuisine:
            entity_id: binary_sensor.capteur_motion_cuisine
            friendly_name: Batterie Hue sensor Cuisine
            unit_of_measurement: '%'
            value_template: '{{ states.binary_sensor.capteur_motion_cuisine.attributes.battery }}'
            icon_template: >-
                {% set battery_level = states('sensor.battery_hue_sensor_cuisine')|int('unknown') %}
                {% set battery_round = (battery_level|int / 10)|int * 10 %}
                {% if battery_level == 'unknown' %}
                  mdi:battery-unknown
                {% else %}
                  {% if battery_round >= 100 %}
                    mdi:battery
                  {% elif battery_round > 0 %}
                    mdi:battery-{{ battery_round }}
                  {% else %}
                    mdi:battery-alert
                  {% endif %}
                {% endif %}

binary_sensor:
  - platform: hue

#script:
#    hue_soiree_tv:
#        alias: Scène soirée TV
#        sequence:
#          - service: hue.hue_activate_scene
#            data:
#                group_name: "Salon"
#                scene_name: "Détente"
#    hue_veilleuse_hugo:
#        alias: Scène Veilleuse Hugo
#        sequence:
#          - service: hue.hue_activate_scene
#            data:
#                group_name: "Chambre"
#                scene_name: "Détente"
#    hue_debut_soiree:
#        alias: Début de soirée
#        sequence:
#          - service: hue.hue_activate_scene
#            data:
#                group_name: "Salon"
#                scene_name: "Lecture"

switch:
  - platform: flux
    start_time: '07:00'
    stop_time: '21:00'
    lights:
      - light.spot_bibliotheque
      - light.spot_entree
      - light.spot_salon
      - light.spot_salon_couloir
      - light.plafonnier_salon
      - light.lampe_du_cube
      - light.caisson_de_basse
    mode: xy

  - platform: flux
    name: "Flux Meuble TV"
    start_time: '07:00'
    stop_time: '21:00'
    lights:
      - light.meuble_tv
    mode: rgb
    brightness: 128
    
  - platform: flux
    name: "Flux Cuisine"
    start_time: '07:00'
    stop_time: '21:00'
    mode: mired
    disable_brightness_adjust: True
    lights:
      - light.cuisine

  - platform: flux
    name: "Flux Couloir"
    start_time: '07:00'
    stop_time: '21:00'
    mode: mired
    lights:
      - light.couloir
