###############################################################################
# PACKAGE:      meteo
###############################################################################
sensor:
  - platform: wunderground
    api_key: !secret wunderground_api_key
    lang: FR
    monitored_conditions:
      - weather_1d_metric
      - weather_1n_metric
      - weather_2d_metric
      - weather_2n_metric
      - weather_3d_metric
      - weather_3n_metric
      - weather_4d_metric
      - weather_4n_metric
      - temp_high_record_c
      - temp_high_1d_c
      - temp_c
      - temp_low_1d_c
      - temp_low_record_c
      - precip_1d
      - precip_1d_mm
      - wind_kph
      - wind_dir
      - wind_gust_1d_kph
      - wind_1d_kph
      - alerts

  - platform: yr
    monitored_conditions:
      - symbol

  - platform: meteo_france
    postal_code: '06200'
    monitored_conditions:
      - temperature
      - weather
      - wind_speed
      - uv
      - freeze_chance
      - rain_chance
      - snow_chance
      - thunder_chance

weather:
  - platform: darksky
    api_key: 'fe0253ccb00d28ff8c224d0b084c3aff'
    mode: 'daily'
