neato:
    username: !secret neato_username
    password: !secret neato_password

input_boolean:
    neato_started:

sensor:
  - platform: template
    sensors:
      neato_area:
        friendly_name: "Neato: Surface nettoyé"
        entity_id: vacuum.ganondorf
        value_template: "Area Cleaned: {{ states.vacuum.ganondorf.attributes.clean_area | round(1) }}"
        unit_of_measurement: 'm²'
      neato_status:
        friendly_name: "Neato: Status"
        entity_id: vacuum.ganondorf
        value_template: "Status: {{ states.vacuum.ganondorf.attributes.status }}"
      neato_battery:
        friendly_name: "Batterie: neato"
        entity_id: vacuum.ganondorf
        value_template: "{{ states.vacuum.ganondorf.attributes.battery_level }}"
        unit_of_measurement: '%'
