homeassistant:
    customize:
        sensor.living_room_nest_protect_battery_health:
            friendly_name: Batterie Nest Protect
        sensor.living_room_nest_protect_smoke_status:
            friendly_name: Détecteur de fumée
        sensor.living_room_nest_protect_co_status:
            friendly_name: Détecteur de Monoxyde de Carbone

nest:
    client_id: !secret nest_client_id
    client_secret: !secret nest_client_secret
