sensor:
  - platform: speedtest
    monitored_conditions:
      - ping
      - download
      - upload

  - platform: statistics
    entity_id: sensor.speedtest_download
    name: Stats Speedtest download
  
  - platform: statistics
    entity_id: sensor.speedtest_upload
    name: Stats Speedtest upload
