climate:
  - platform: zwave

binary_sensor:
  - platform: template
    entity_id: sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control
    sensors:
        capteur_ouverture:
            device_class: opening
            friendly_name: 'Porte/Fenetre'
            value_template: "{{ not is_state('sensor.fibaro_system_fgdw002_door_opening_sensor_2_access_control', '23') }}"

sensor:
  - platform: template
    sensors:
        battery_multisensor:
            entity_id: zwave.aeotec_zw100_multisensor_6
            friendly_name: Batterie Multisensor Entrée
            unit_of_measurement: '%'
            value_template: '{{ states.zwave.aeotec_zw100_multisensor_6.attributes.battery_level }}'
            icon_template: >-
                {% set battery_level = states('sensor.battery_multisensor')|int('unknown') %}
                {% set battery_round = (battery_level|int / 10)|int * 10 %}
                {% if battery_level == 'unknown' %}
                  mdi:battery-unknown
                {% else %}
                  {% if battery_round >= 100 %}
                    mdi:battery
                  {% elif battery_round > 0 %}
                    mdi:battery-{{ battery_round }}
                  {% else %}
                    mdi:battery-alert
                  {% endif %}
                {% endif %}
        battery_detecteur_inondation:
            entity_id: zwave.detecteur_inondation
            friendly_name: Batterie Détecteur Inondation
            unit_of_measurement: '%'
            value_template: '{{ states.zwave.detecteur_inondation.attributes.battery_level }}'
            icon_template: >-
                {% set battery_level = states('sensor.battery_detecteur_inondation')|int('unknown') %}
                {% set battery_round = (battery_level|int / 10)|int * 10 %}
                {% if battery_level == 'unknown' %}
                  mdi:battery-unknown
                {% else %}
                  {% if battery_round >= 100 %}
                    mdi:battery
                  {% elif battery_round > 0 %}
                    mdi:battery-{{ battery_round }}
                  {% else %}
                    mdi:battery-alert
                  {% endif %}
                {% endif %}
        battery_sensor_door:
            entity_id: zwave.fibaro_system_fgdw002_door_opening_sensor_2
            friendly_name: Batterie Détecteur Porte
            unit_of_measurement: '%'
            value_template: '{{ states.zwave.fibaro_system_fgdw002_door_opening_sensor_2.attributes.battery_level }}'
            icon_template: >-
                {% set battery_level = states('sensor.battery_sensor_door')|int('unknown') %}
                {% set battery_round = (battery_level|int / 10)|int * 10 %}
                {% if battery_level == 'unknown' %}
                  mdi:battery-unknown
                {% else %}
                  {% if battery_round >= 100 %}
                    mdi:battery
                  {% elif battery_round > 0 %}
                    mdi:battery-{{ battery_round }}
                  {% else %}
                    mdi:battery-alert
                  {% endif %}
                {% endif %}
